name: "Unit tests / Cover"

on:
  pull_request:
    branches:
      - master


jobs:

  run-unittests:
    name: unit-${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install nox
      run: |
        python -m pip install --upgrade setuptools pip wheel
        python -m pip install tox

    - name: Run unit tests
      run: |
        tox -e py${{ matrix.python }}

  run-unittests-w-deps:
    name: unit-w-deps
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install tox
      run: |
        python -m pip install --upgrade setuptools pip wheel
        python -m pip install tox

    - name: Run unit tests
      run: |
        tox -e w_deps

  report-coverage:
    name: cover
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - run: pip install tox
    - run: tox -e py312-cover,w_deps,cover
